"""empty message

Revision ID: e60036ecf6c1
Revises: 870bbb697743
Create Date: 2021-11-09 18:01:21.339543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60036ecf6c1'
down_revision = '870bbb697743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('edit_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'edit_date')
    # ### end Alembic commands ###
